# Generated by Django 5.1.5 on 2025-01-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default='+390000000000', max_length=15),
        ),
    ]
