# Generated by Django 5.1.5 on 2025-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='available_times',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='reservation',
            name='group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='max_people',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
