# Generated by Django 5.1.5 on 2025-02-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_available_times_reservation_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
